# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

products:
    path: /{_locale}/products
    controller: App\Controller\ProductController::index
    requirements:
        _locale: en|sr

footballClub:
    path: /football/club
    controller: App\Controller\FootballClubController::index
    requirements:
        _locale: en|sr
